### ISSUE TITLE
Cannot permanently install vuiet into doom emacs...cannot find versuri

### ISSUE THREAD

**Issue by eklebanow** [mihaiolteanu/vuiet#22] opened 2020-04-12 05:48 UTC
Using doome emacs I can install and use vuiet by cloning vuiet repo onto my computer and then installing vuiet from within emacs doom using install from file and pointing to the vuiet package. 
 When I play tracks i can bring up lyrics
but this install is not permanent  So to make permanent I tried the following code

(package! vuiet
  :recipe (:host github :repo "mihaiolteanu/vuiet"))

I get error message upon running my config files that says that versuri is not found.  I have googled versuri and I cannot find the package anywhere.....??

I am confused as to why when I install the vuiet as a file from the package on my computer it has no issue with vuiet/versuri while when I point it to the repo for a permanent install I get error that versuri not found.....

**Comment by mihaiolteanu** [comment] 2020-04-12 06:12
> I have googled versuri and I cannot find the package anywhere

Here it is: https://github.com/mihaiolteanu/versuri

> I am confused as to why when I install the vuiet as a file from the package on my computer it has no issue with vuiet/versuri while when I point it to the repo for a permanent install I get error that versuri not found

I assume that when you

> install from file and pointing to the vuiet package

it gets to see the requirements list at the top of the vuiet.el file, which looks like this,
```
;; Package-Requires: ((emacs "26.1") (lastfm "1.1") (versuri "1.0") (s "1.12.0") (bind-key "2.4") (mpv "0.1.0"))
```
and knows what it needs to install (from [melpa](https://melpa.org/#/) to run vuiet, which is not the case with the code you provided. Again, this is only an assumption. I'm not using doom emacs, so I wouldn't exactly know. This doesn't mean that this shouldn't be fixed, if there is something to be fixed from vuiet side. I'm open to suggestions if anybody knows where the problem is or if you can provide more info.

Thanks for bringing this up!

**Comment by mihaiolteanu** [comment] 2020-04-12 06:19
Do you have a `use-package!` form anywhere in your init code?
Please see this issue on doom-emacs: https://github.com/hlissner/doom-emacs/issues/1773
Again, this is just an assumption on my part. I'm not really knowledgeable with doom-emacs.
Let me know what you came up with.

**Comment by mihaiolteanu** [comment] 2020-04-12 11:32
I assume this is something similar with #23.
And since you're not replying to my comments, I will close this for the moment.

**Closed as completed by mihaiolteanu** 2020-04-12 11:32 UTC

**Comment by eklebanow** [comment] 2020-04-13 01:15
I thank you for your patience with me...

I am still not able to get an authorized token to allow me to get a SK.

I have tried everything I can think of including setting up several lastfm account with different emails.

When requesting the API I am asked the following:
Contact email (klebane@gmail.com)
Application name (Spotify)
App description (left blank)
Callback url (left blank)
App homepage (left blank)

I click Submit

It sends me API.......

Am I doing something wrong here?

Again thanks for your patience.....

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mihaiolteanu** [comment] 2020-04-13 07:08
I'm sending you this link for the third time now, but you still don't want to read it :)
https://github.com/mihaiolteanu/lastfm.el#install

**Comment by eklebanow** [comment] 2020-04-13 20:13
Mihai

Please help me... This is not a game to me.... Yes I get it.... It's like a chat room where people answer RTFM....

I cannot figure out what I am missing....I have read through the instructions several times but I cannot figure out how to get an authorized token

I have two doctorate degrees... Medical...I try to do my homework before asking someone to take their valuable time to help me through an email issue

Thank you in advance for helping me walk through what I am missing to get an authorized token

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by eklebanow** [comment] 2020-04-15 01:54
Mihai

To get a secret key do you have to include a callback url when you request an API?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
